spring.application.name=agendador-tarefas

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/db_agendador}
spring.data.mongodb.auto-index-creation=true

# Feign
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000
spring.cloud.openfeign.client.config.default.logger-level=basic

# URL do serviço de Usuário
usuario.url=${USUARIO_SERVICE_URL:http://localhost:8080}

# JWT (MESMA CHAVE do serviço usuario!)
jwt.secret=${JWT_SECRET:MinhaChaveSuperSecretaComMaisDe256BitsParaSerSeguraEValidaNoHS256Algorithm}

# Server
server.port=8081

# Logging
logging.level.com.javanauta.agendadortarefas=INFO
logging.level.feign=DEBUG